# Generated by Django 5.2.9 on 2026-01-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Official rank for this task (1-N)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_rankings', to='core.stage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_rankings', to='core.task')),
            ],
            options={
                'ordering': ['stage', 'rank'],
                'unique_together': {('stage', 'task')},
            },
        ),
    ]
